# you can ignore this for now
datasets:
  - name: ignore

#Your connection
connections:
  - name: Virtuoso
    endpoint: http://ec2-18-170-45-162.eu-west-2.compute.amazonaws.com:8890/sparql

tasks:
  - className: Stresstest
    configuration:
      timeLimit: 3600000 # ms
      queryHandler:
        className: InstancesQueryHandler
      workers:
        - threads: 2
          className: SPARQLWorker
          queriesFile: queries.txt
          timeOut: 180000

metrics:
  - className: QMPH
  - className: QPS
  - className: NoQPH
  - className: NoQ
  - className: AvgQPS

storages:
  - className: NTFileStorage
