SELECT distinct ?v0 ?v1 ?v2 ?v3 ?v5 ?v6 ?v7 ?v10
WHERE 
{ 
    ?v0 rdfs:comment ?v1 .
    ?v0 foaf:page %% v %%
    OPTIONAL { ?v0 skos:subject ?v6 } 
    OPTIONAL { ?v0 dbp-prop:industry ?v5 } 
    OPTIONAL {?v0 dbp-prop:location ?v2 }



    OPTIONAL { ?v0 dbp-prop:locationCountry ?v3 } 
    OPTIONAL {
        ?v0 dbp-prop:locationCity ?v9 ; 
            dbp-prop:manufacturer ?v0 
    } 
    OPTIONAL { ?v0 dbp-prop:products ?v11 ; 
                dbp-prop:model ?v0 
    } 
    OPTIONAL { ?v0 georss:point ?v10 } 
    OPTIONAL { ?v0 rdf:type ?v7 }
}