SELECT ?v1
WHERE
{
    { ?v1 rdfs:label %% v %% . } 
    UNION 
    { ?v1 rdfs:label %% v %% . }
    FILTER (
        regex(str(?v1), 'http://dbpedia.org/resource/') 
        || regex(str(?v1), 'http://dbpedia.org/ontology/') 
        || regex(str(?v1), 'http://www.w3.org/2002/07/owl') 
        || regex(str(?v1), 'http:// www.w3.org /2001/ XMLSchema') 
        || regex(str(?v1), 'http:// www.w3.org /2000/01/ rdf-schema') 
        || regex(str(?v1), 'http:// www.w3.org /1999/02/22-rdf-syntax-ns')
    ) 
}